version: "3"
services:
  api:
    image: pashathecreator/social-network-api-api
    depends_on:
      - postgres
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports: [ 8000:8000 ]
    volumes:
      - ./:/usr/src/app:ro
    env_file: ./.env

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file: ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
